import fs from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { defineConfig, type Plugin } from 'vite'
import vue from '@vitejs/plugin-vue'
import ui from '@nuxt/ui/vite'
import { getIcons } from '@iconify/utils/lib/icon-set/get-icons.js'
import type { IconifyJSON } from '@iconify/types'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const require = createRequire(import.meta.url)

function readDevCert(): { cert: Buffer; key: Buffer } | null {
  const certPath = path.resolve(__dirname, '.certs/dev.pem')
  const keyPath  = path.resolve(__dirname, '.certs/dev-key.pem')
  if (!fs.existsSync(certPath) || !fs.existsSync(keyPath)) return null
  return { cert: fs.readFileSync(certPath), key: fs.readFileSync(keyPath) }
}

// Copies the right manifest into dist/manifest.xml at build time. Manifests are baked at build
// time (per-environment images), no runtime substitution.
//
//   production → manifest.xml (prod manifest, targets https://outlook.retyc.com — for non-prod
//                envs, swap this file with a gitignored manifest.<env>.xml before docker build).
//   anything else → manifest.dev.xml (generated by `npm run dev:setup` against DEV_HOST).
//
// Dev builds fail loudly when manifest.dev.xml is missing so we can never accidentally ship a
// `outlook.retyc.com`-pointing manifest from a local dev server.
function manifestCopyPlugin(mode: string): Plugin {
  const source = mode === 'production' ? 'manifest.xml' : 'manifest.dev.xml'
  const sourcePath = path.resolve(__dirname, source)
  return {
    name: 'retyc:copy-manifest',
    apply: 'build',
    buildStart() {
      if (mode !== 'production' && !fs.existsSync(sourcePath)) {
        throw new Error(`${source} missing — run \`npm run dev:setup\` first.`)
      }
    },
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: 'manifest.xml',
        source: fs.readFileSync(sourcePath),
      })
    },
  }
}

// Bundles only the Lucide icons actually referenced in src/** as `i-lucide-<name>`.
// Replaces a 540 kB `@iconify-json/lucide/icons.json` import with a ~few-kB subset.
function lucideSubsetPlugin(): Plugin {
  const virtualId = 'virtual:lucide-subset'
  const resolvedId = '\0' + virtualId
  const srcDir = path.resolve(__dirname, 'src')
  const re = /i-lucide-([a-z0-9-]+)/g

  function collectUsedIcons(): string[] {
    const used = new Set<string>()
    const entries = fs.readdirSync(srcDir, { recursive: true, withFileTypes: true }) as fs.Dirent[]
    for (const entry of entries) {
      if (!entry.isFile()) continue
      if (!/\.(ts|vue|html)$/.test(entry.name)) continue
      const dir = (entry as fs.Dirent & { parentPath?: string }).parentPath ?? srcDir
      const text = fs.readFileSync(path.join(dir, entry.name), 'utf8')
      for (const m of text.matchAll(re)) used.add(m[1])
    }
    return [...used].sort()
  }

  return {
    name: 'retyc:lucide-subset',
    resolveId(id) {
      return id === virtualId ? resolvedId : null
    },
    load(id) {
      if (id !== resolvedId) return null
      const names = collectUsedIcons()
      const full = require('@iconify-json/lucide/icons.json') as IconifyJSON
      const subset = getIcons(full, names)
      if (!subset) throw new Error('lucide-subset: failed to extract any icons')
      const known = new Set([...Object.keys(subset.icons ?? {}), ...Object.keys(subset.aliases ?? {})])
      const missing = names.filter(n => !known.has(n))
      if (missing.length > 0) {
        this.warn(`lucide-subset: unknown icons referenced: ${missing.join(', ')}`)
      }
      return `export default ${JSON.stringify(subset)}`
    },
  }
}

const redirectRootPlugin: Plugin = {
  name: 'retyc:redirect-root',
  apply: 'serve',
  configureServer(server) {
    server.middlewares.use((req, res, next) => {
      if (req.url === '/') {
        res.writeHead(302, { Location: '/taskpane.html' })
        res.end()
        return
      }
      next()
    })
  },
}

export default defineConfig(({ mode }) => {
  const devCert = readDevCert()

  return {
    plugins: [
      vue(),
      lucideSubsetPlugin(),
      redirectRootPlugin,
      ui({
        colorMode: false,
        router:    false,
        ui: {
          colors: {
            primary:   'cornflower-blue',
            secondary: 'jacaranda',
            neutral:   'zinc',
          },
          button: {
            slots: {
              base: 'cursor-pointer',
            },
          },
          tabs: {
            slots: {
              trigger: 'cursor-pointer',
            },
          },
        },
      }),
      manifestCopyPlugin(mode),
    ],

    resolve: {
      alias: {
        'node:buffer':  'buffer',
        'node:stream':  'stream-browserify',
        'node:path':    path.resolve(__dirname, 'node_modules/path-browserify/index.js'),
        'fs':           path.resolve(__dirname, 'src/shims/fs.ts'),
        'path':         path.resolve(__dirname, 'node_modules/path-browserify/index.js'),
      },
    },

    define: {
      'process.env':    '{}',
      'global':         'globalThis',
    },

    optimizeDeps: {
      include: ['buffer', 'stream-browserify', 'path-browserify'],
    },

    publicDir: 'public',

    build: {
      outDir: 'dist',
      rolldownOptions: {
        input: path.resolve(__dirname, 'taskpane.html'),
        output: {
          entryFileNames: '[name].js',
          chunkFileNames: 'chunks/[name]-[hash].js',
          assetFileNames: '[name].[ext]',
          codeSplitting: {
            groups: [
              { name: 'sdk', test: /(?:[\\/]retyc-ts-sdk[\\/]|[\\/]node_modules[\\/](@retyc[\\/]sdk|jose|buffer|stream-browserify|path-browserify)[\\/])/ },
              { name: 'ui', test: /[\\/]node_modules[\\/]@nuxt[\\/]ui[\\/]/ },
              { name: 'reka', test: /[\\/]node_modules[\\/](reka-ui|@vueuse[\\/]core|@floating-ui|@iconify[\\/]vue)[\\/]/ },
              { name: 'vendor', test: /[\\/]node_modules[\\/]/ },
            ],
          },
        },
      },
    },

    server: {
      port:  3000,
      host:  '0.0.0.0',
      https: devCert ?? undefined,
    },
  }
})
